version: '3'

services:

  db:
    image: postgres
    restart: always
    container_name: postgres
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}

  test-db:
    image: postgres
    restart: always
    container_name: test-postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}

  app:
    build: .
    image: ng
    container_name: app
    depends_on:
      - db
    ports:
      - ${APP_PORT}:3000
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}
      BCRYPT_SALT: ${BCRYPT_SALT}
      TYPEORM_SYNCHRONIZE: false
